-- VCMAS 001: initial MySQL schema
-- Target: MariaDB 10.4+ (XAMPP) or MySQL 8.0.16+
-- Run after selecting the VCMAS database. UUID values are generated by the API.

SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS roles (
  id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  code VARCHAR(32) NOT NULL,
  name VARCHAR(80) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_roles_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO roles (code, name) VALUES
  ('administrator', 'Administrator'),
  ('veterinarian', 'Veterinarian'),
  ('staff', 'Clinic Staff'),
  ('client', 'Client');

CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) NOT NULL,
  role_id TINYINT UNSIGNED NOT NULL,
  email VARCHAR(254) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(160) NOT NULL,
  phone VARCHAR(32) NULL,
  status ENUM('active', 'inactive', 'locked') NOT NULL DEFAULT 'active',
  last_login_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_email (email),
  KEY idx_users_role_status (role_id, status),
  CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS clinic_settings (
  id TINYINT UNSIGNED NOT NULL,
  clinic_name VARCHAR(160) NOT NULL,
  address VARCHAR(255) NOT NULL,
  mobile_number VARCHAR(32) NULL,
  telephone_number VARCHAR(32) NULL,
  opening_time TIME NOT NULL,
  closing_time TIME NOT NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Manila',
  logo_path VARCHAR(255) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  CONSTRAINT chk_clinic_settings_singleton CHECK (id = 1),
  CONSTRAINT chk_clinic_settings_hours CHECK (opening_time < closing_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS clients (
  id CHAR(36) NOT NULL,
  user_id CHAR(36) NULL,
  full_name VARCHAR(160) NOT NULL,
  email VARCHAR(254) NOT NULL,
  phone VARCHAR(32) NULL,
  address VARCHAR(255) NULL,
  emergency_contact_name VARCHAR(160) NULL,
  emergency_contact_phone VARCHAR(32) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_clients_user_id (user_id),
  KEY idx_clients_email (email),
  CONSTRAINT fk_clients_user FOREIGN KEY (user_id) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS services (
  id CHAR(36) NOT NULL,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(160) NOT NULL,
  description TEXT NULL,
  category VARCHAR(80) NULL,
  price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  tax_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_services_code (code),
  KEY idx_services_active_category (active, category),
  CONSTRAINT chk_services_price CHECK (price >= 0),
  CONSTRAINT chk_services_tax_rate CHECK (tax_rate >= 0 AND tax_rate <= 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pets (
  id CHAR(36) NOT NULL,
  client_id CHAR(36) NOT NULL,
  name VARCHAR(120) NOT NULL,
  species VARCHAR(80) NOT NULL,
  breed VARCHAR(120) NULL,
  photo_path VARCHAR(255) NULL,
  alerts TEXT NULL,
  sex ENUM('female', 'male', 'unknown') NOT NULL DEFAULT 'unknown',
  date_of_birth DATE NULL,
  weight_kg DECIMAL(7,3) NULL,
  status ENUM('active', 'inactive', 'deceased') NOT NULL DEFAULT 'active',
  allergies TEXT NULL,
  chronic_conditions TEXT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_pets_client_status (client_id, status),
  KEY idx_pets_name_species (name, species),
  CONSTRAINT fk_pets_client FOREIGN KEY (client_id) REFERENCES clients (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_pets_weight CHECK (weight_kg IS NULL OR weight_kg > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS appointments (
  id CHAR(36) NOT NULL,
  client_id CHAR(36) NOT NULL,
  pet_id CHAR(36) NOT NULL,
  veterinarian_id CHAR(36) NULL,
  service_id CHAR(36) NULL,
  room VARCHAR(80) NULL,
  starts_at DATETIME(6) NOT NULL,
  ends_at DATETIME(6) NOT NULL,
  status ENUM('requested', 'scheduled', 'checked_in', 'in_progress', 'completed', 'cancelled', 'no_show') NOT NULL DEFAULT 'requested',
  reason VARCHAR(255) NULL,
  notes TEXT NULL,
  cancellation_reason VARCHAR(255) NULL,
  created_by CHAR(36) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_appointments_schedule (starts_at, ends_at, status),
  KEY idx_appointments_pet_date (pet_id, starts_at),
  KEY idx_appointments_client_date (client_id, starts_at),
  KEY idx_appointments_veterinarian_date (veterinarian_id, starts_at),
  CONSTRAINT fk_appointments_client FOREIGN KEY (client_id) REFERENCES clients (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_appointments_pet FOREIGN KEY (pet_id) REFERENCES pets (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_appointments_veterinarian FOREIGN KEY (veterinarian_id) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_appointments_service FOREIGN KEY (service_id) REFERENCES services (id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_appointments_created_by FOREIGN KEY (created_by) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_appointments_time CHECK (starts_at < ends_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS emr_visits (
  id CHAR(36) NOT NULL,
  pet_id CHAR(36) NOT NULL,
  appointment_id CHAR(36) NULL,
  author_id CHAR(36) NOT NULL,
  visited_at DATETIME(6) NOT NULL,
  weight_kg DECIMAL(7,3) NULL,
  temperature_c DECIMAL(4,1) NULL,
  chief_complaint TEXT NULL,
  clinical_notes TEXT NOT NULL,
  diagnosis TEXT NULL,
  treatment_plan TEXT NULL,
  follow_up_instructions TEXT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_emr_visits_appointment (appointment_id),
  KEY idx_emr_visits_pet_date (pet_id, visited_at),
  CONSTRAINT fk_emr_visits_pet FOREIGN KEY (pet_id) REFERENCES pets (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_emr_visits_appointment FOREIGN KEY (appointment_id) REFERENCES appointments (id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_emr_visits_author FOREIGN KEY (author_id) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_emr_visit_weight CHECK (weight_kg IS NULL OR weight_kg > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS emr_vaccinations (
  id CHAR(36) NOT NULL,
  pet_id CHAR(36) NOT NULL,
  visit_id CHAR(36) NULL,
  vaccine_name VARCHAR(160) NOT NULL,
  administered_at DATETIME(6) NOT NULL,
  next_due_at DATE NULL,
  batch_number VARCHAR(80) NULL,
  administered_by CHAR(36) NOT NULL,
  notes TEXT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_emr_vaccinations_pet_date (pet_id, administered_at),
  CONSTRAINT fk_emr_vaccinations_pet FOREIGN KEY (pet_id) REFERENCES pets (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_emr_vaccinations_visit FOREIGN KEY (visit_id) REFERENCES emr_visits (id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_emr_vaccinations_user FOREIGN KEY (administered_by) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS emr_laboratory_results (
  id CHAR(36) NOT NULL,
  pet_id CHAR(36) NOT NULL,
  visit_id CHAR(36) NULL,
  test_name VARCHAR(160) NOT NULL,
  status ENUM('ordered', 'collected', 'available', 'reviewed', 'cancelled') NOT NULL DEFAULT 'ordered',
  result_summary TEXT NULL,
  result_path VARCHAR(255) NULL,
  ordered_at DATETIME(6) NOT NULL,
  reviewed_at DATETIME(6) NULL,
  reviewed_by CHAR(36) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_emr_labs_pet_date (pet_id, ordered_at),
  CONSTRAINT fk_emr_labs_pet FOREIGN KEY (pet_id) REFERENCES pets (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_emr_labs_visit FOREIGN KEY (visit_id) REFERENCES emr_visits (id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_emr_labs_reviewer FOREIGN KEY (reviewed_by) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS emr_medications (
  id CHAR(36) NOT NULL,
  pet_id CHAR(36) NOT NULL,
  visit_id CHAR(36) NULL,
  medication_name VARCHAR(160) NOT NULL,
  dosage VARCHAR(120) NULL,
  route VARCHAR(80) NULL,
  frequency VARCHAR(120) NULL,
  starts_on DATE NULL,
  ends_on DATE NULL,
  instructions TEXT NULL,
  prescribed_by CHAR(36) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_emr_medications_pet_date (pet_id, starts_on),
  CONSTRAINT fk_emr_medications_pet FOREIGN KEY (pet_id) REFERENCES pets (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_emr_medications_visit FOREIGN KEY (visit_id) REFERENCES emr_visits (id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_emr_medications_prescriber FOREIGN KEY (prescribed_by) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_emr_medications_dates CHECK (ends_on IS NULL OR starts_on IS NULL OR starts_on <= ends_on)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_items (
  id CHAR(36) NOT NULL,
  sku VARCHAR(80) NULL,
  name VARCHAR(180) NOT NULL,
  category ENUM('drugs', 'medical_items', 'laboratory_equipment', 'pet_food', 'pet_supplies', 'other') NOT NULL,
  unit VARCHAR(40) NOT NULL,
  supplier_name VARCHAR(160) NULL,
  quantity_on_hand DECIMAL(12,3) NOT NULL DEFAULT 0.000,
  reorder_level DECIMAL(12,3) NOT NULL DEFAULT 0.000,
  unit_cost DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  client_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  chargeable BOOLEAN NOT NULL DEFAULT TRUE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_inventory_items_sku (sku),
  KEY idx_inventory_items_category_active (category, active),
  KEY idx_inventory_items_reorder (active, quantity_on_hand, reorder_level),
  CONSTRAINT chk_inventory_items_quantity CHECK (quantity_on_hand >= 0),
  CONSTRAINT chk_inventory_items_reorder CHECK (reorder_level >= 0),
  CONSTRAINT chk_inventory_items_cost CHECK (unit_cost >= 0),
  CONSTRAINT chk_inventory_items_price CHECK (client_price >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoices (
  id CHAR(36) NOT NULL,
  invoice_number VARCHAR(40) NOT NULL,
  client_id CHAR(36) NOT NULL,
  pet_id CHAR(36) NULL,
  appointment_id CHAR(36) NULL,
  status ENUM('draft', 'issued', 'partially_paid', 'paid', 'void', 'refunded') NOT NULL DEFAULT 'draft',
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  tax_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  discount_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  amount_paid DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  balance_due DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  issued_at DATETIME(6) NULL,
  due_at DATETIME(6) NULL,
  created_by CHAR(36) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_invoices_number (invoice_number),
  KEY idx_invoices_client_status (client_id, status),
  KEY idx_invoices_pet_date (pet_id, created_at),
  CONSTRAINT fk_invoices_client FOREIGN KEY (client_id) REFERENCES clients (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_invoices_pet FOREIGN KEY (pet_id) REFERENCES pets (id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_invoices_appointment FOREIGN KEY (appointment_id) REFERENCES appointments (id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_invoices_created_by FOREIGN KEY (created_by) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_invoices_amounts CHECK (
    subtotal >= 0 AND tax_total >= 0 AND discount_total >= 0 AND
    total >= 0 AND amount_paid >= 0 AND balance_due >= 0
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_transactions (
  id CHAR(36) NOT NULL,
  inventory_item_id CHAR(36) NOT NULL,
  type ENUM('purchase', 'patient_usage', 'return', 'wastage', 'correction') NOT NULL,
  quantity_delta DECIMAL(12,3) NOT NULL,
  quantity_before DECIMAL(12,3) NOT NULL,
  quantity_after DECIMAL(12,3) NOT NULL,
  unit_cost DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  client_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  patient_id CHAR(36) NULL,
  visit_id CHAR(36) NULL,
  appointment_id CHAR(36) NULL,
  invoice_id CHAR(36) NULL,
  reverses_transaction_id CHAR(36) NULL,
  reason VARCHAR(255) NOT NULL,
  client_request_id VARCHAR(100) NOT NULL,
  created_by CHAR(36) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_inventory_transactions_request (client_request_id),
  KEY idx_inventory_transactions_item_date (inventory_item_id, created_at),
  KEY idx_inventory_transactions_patient_date (patient_id, created_at),
  KEY idx_inventory_transactions_invoice (invoice_id),
  CONSTRAINT fk_inventory_transactions_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_inventory_transactions_patient FOREIGN KEY (patient_id) REFERENCES pets (id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_inventory_transactions_visit FOREIGN KEY (visit_id) REFERENCES emr_visits (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_inventory_transactions_reversal FOREIGN KEY (reverses_transaction_id) REFERENCES inventory_transactions (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_inventory_transactions_appointment FOREIGN KEY (appointment_id) REFERENCES appointments (id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_inventory_transactions_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_inventory_transactions_created_by FOREIGN KEY (created_by) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_inventory_transactions_quantity CHECK (quantity_delta <> 0 AND quantity_before >= 0 AND quantity_after >= 0 AND quantity_after = quantity_before + quantity_delta),
  CONSTRAINT chk_inventory_transactions_direction CHECK (
    (type = 'purchase' AND quantity_delta > 0) OR
    (type IN ('patient_usage', 'wastage') AND quantity_delta < 0) OR
    type IN ('return', 'correction')
  ),
  CONSTRAINT chk_inventory_transactions_patient_usage CHECK (type <> 'patient_usage' OR patient_id IS NOT NULL),
  CONSTRAINT chk_inventory_transactions_amounts CHECK (unit_cost >= 0 AND client_price >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoice_lines (
  id CHAR(36) NOT NULL,
  invoice_id CHAR(36) NOT NULL,
  line_type ENUM('service', 'inventory', 'adjustment') NOT NULL,
  description VARCHAR(255) NOT NULL,
  service_id CHAR(36) NULL,
  inventory_transaction_id CHAR(36) NULL,
  quantity DECIMAL(12,3) NOT NULL DEFAULT 1.000,
  unit_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  line_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  reverses_line_id CHAR(36) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_invoice_lines_inventory_transaction (inventory_transaction_id),
  KEY idx_invoice_lines_invoice (invoice_id),
  CONSTRAINT fk_invoice_lines_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_invoice_lines_service FOREIGN KEY (service_id) REFERENCES services (id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_invoice_lines_reversal FOREIGN KEY (reverses_line_id) REFERENCES invoice_lines (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_invoice_lines_inventory_transaction FOREIGN KEY (inventory_transaction_id) REFERENCES inventory_transactions (id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT chk_invoice_lines_amounts CHECK (
    quantity <> 0 AND unit_price >= 0 AND
    (line_type = 'adjustment' OR (quantity > 0 AND tax_amount >= 0 AND line_total >= 0))
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_expenses (
  id CHAR(36) NOT NULL,
  inventory_transaction_id CHAR(36) NOT NULL,
  supplier_name VARCHAR(160) NULL,
  purchase_reference VARCHAR(100) NULL,
  amount DECIMAL(12,2) NOT NULL,
  status ENUM('unpaid', 'paid', 'cancelled') NOT NULL DEFAULT 'unpaid',
  created_by CHAR(36) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_inventory_expenses_transaction (inventory_transaction_id),
  CONSTRAINT fk_inventory_expenses_transaction FOREIGN KEY (inventory_transaction_id) REFERENCES inventory_transactions (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_inventory_expenses_created_by FOREIGN KEY (created_by) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_inventory_expenses_amount CHECK (amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payments (
  id CHAR(36) NOT NULL,
  invoice_id CHAR(36) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  method ENUM('cash', 'card', 'bank_transfer', 'gcash', 'other') NOT NULL,
  status ENUM('pending', 'completed', 'void', 'refunded') NOT NULL DEFAULT 'completed',
  reference VARCHAR(120) NULL,
  paid_at DATETIME(6) NOT NULL,
  received_by CHAR(36) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_payments_invoice_date (invoice_id, paid_at),
  CONSTRAINT fk_payments_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_payments_received_by FOREIGN KEY (received_by) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_payments_amount CHECK (amount > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS client_notifications (
  id CHAR(36) NOT NULL,
  client_id CHAR(36) NOT NULL,
  type VARCHAR(64) NOT NULL,
  message VARCHAR(500) NOT NULL,
  read_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_notifications_client_read_date (client_id, read_at, created_at),
  CONSTRAINT fk_notifications_client FOREIGN KEY (client_id) REFERENCES clients (id)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_events (
  id CHAR(36) NOT NULL,
  actor_user_id CHAR(36) NULL,
  action VARCHAR(80) NOT NULL,
  entity_type VARCHAR(80) NOT NULL,
  entity_id CHAR(36) NULL,
  request_id VARCHAR(100) NULL,
  metadata JSON NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_audit_entity_date (entity_type, entity_id, created_at),
  KEY idx_audit_actor_date (actor_user_id, created_at),
  KEY idx_audit_request (request_id),
  CONSTRAINT fk_audit_actor FOREIGN KEY (actor_user_id) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS auth_sessions (
  id CHAR(36) NOT NULL,
  user_id CHAR(36) NOT NULL,
  token_hash CHAR(64) NOT NULL,
  csrf_token_hash CHAR(64) NOT NULL,
  expires_at DATETIME(6) NOT NULL,
  revoked_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_auth_sessions_token (token_hash),
  KEY idx_auth_sessions_user_expiry (user_id, expires_at),
  CONSTRAINT fk_auth_sessions_user FOREIGN KEY (user_id) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS refunds (
  id CHAR(36) NOT NULL,
  payment_id CHAR(36) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  reason VARCHAR(255) NOT NULL,
  client_request_id VARCHAR(100) NOT NULL,
  recorded_by CHAR(36) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_refunds_request (client_request_id),
  CONSTRAINT fk_refunds_payment FOREIGN KEY (payment_id) REFERENCES payments (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_refunds_user FOREIGN KEY (recorded_by) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_refunds_amount CHECK (amount > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS emr_attachments (
  id CHAR(36) NOT NULL,
  pet_id CHAR(36) NOT NULL,
  visit_id CHAR(36) NULL,
  storage_path VARCHAR(255) NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  media_type VARCHAR(100) NOT NULL,
  size_bytes BIGINT UNSIGNED NOT NULL,
  uploaded_by CHAR(36) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_emr_attachments_pet (pet_id, created_at),
  CONSTRAINT fk_emr_attachments_pet FOREIGN KEY (pet_id) REFERENCES pets (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_emr_attachments_visit FOREIGN KEY (visit_id) REFERENCES emr_visits (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_emr_attachments_user FOREIGN KEY (uploaded_by) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schema_migrations (
  version VARCHAR(80) NOT NULL,
  applied_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO schema_migrations (version) VALUES ('001_initial_schema');
